<?php

return [
    'default' => env('CLOUDISHOP_DEFAULT_PLAN', 'free'),

    'plans' => [
        'free' => [
            'name' => 'Free',
            'label' => 'Gratis',
            'price' => 0,
            'currency' => 'MXN',
            'interval' => null,
            'trial_days' => 14,
            'description' => 'Ideal para comenzar a vender sin complicarte.',
            'features' => [
                'Publica tu tienda y valida tu idea.',
                'Configura productos iniciales.',
                'Empieza a recibir tus primeros pedidos.',
            ],
            'limits' => [
                'main_banners' => 1,
                'brand_banners' => 1,
            ],
            'modules' => [
                'dashboard',
                'productos',
                'categorias',
                'familias',
                'pedidos',
                'clientes',
                'banners',
                'configuracion_ecommerce',
                'front_ecommerce',
            ],
        ],

        'basic' => [
            'name' => 'Basico',
            'label' => '$189.00 /mes',
            'price' => 18900,
            'currency' => 'MXN',
            'interval' => 'month',
            'description' => 'Lo esencial para vender con catalogo y operacion simple.',
            'features' => [
                'Catalogo y productos.',
                'Clientes y pedidos.',
                'Configuracion basica.',
                'Plantilla basica incluida.',
            ],
            'limits' => [
                'main_banners' => 3,
                'brand_banners' => 3,
            ],
            'modules' => [
                'dashboard',
                'usuarios',
                'roles',
                'productos',
                'categorias',
                'familias',
                'carga_masiva_productos',
                'variantes',
                'pedidos',
                'carritos',
                'clientes',
                'banners',
                'configuracion_ecommerce',
                'front_ecommerce',
            ],
        ],

        'shop' => [
            'name' => 'Shop',
            'label' => '$429.00 /mes',
            'price' => 42900,
            'currency' => 'MXN',
            'interval' => 'month',
            'description' => 'Para crecer con canales, marketing y experiencias personalizadas.',
            'features' => [
                'Todo lo del plan Basico.',
                'Canales de venta.',
                'Fidelizacion y promociones.',
                'Personalizacion y marketing.',
            ],
            'limits' => [
                'main_banners' => 6,
                'brand_banners' => 6,
            ],
            'modules' => [
                'dashboard',
                'usuarios',
                'roles',
                'productos',
                'categorias',
                'familias',
                'carga_masiva_productos',
                'variantes',
                'pedidos',
                'carritos',
                'clientes',
                'canales_venta',
                'marketing',
                'promociones',
                'banners',
                'logs',
                'configuracion_ecommerce',
                'notificaciones',
                'front_ecommerce',
            ],
        ],

        'shop_plus' => [
            'name' => 'Shop+',
            'label' => '$749.00 /mes',
            'price' => 74900,
            'currency' => 'MXN',
            'interval' => 'month',
            'description' => 'Para equipos que necesitan automatizar, cobrar y conectar mas procesos.',
            'features' => [
                'Todo lo del plan Shop.',
                'Automatizaciones y usuarios.',
                'Conexion con envios.',
                'Recuperacion de carritos.',
                'Credit, cobranza y Kuix.mx.',
            ],
            'limits' => [
                'main_banners' => null,
                'brand_banners' => null,
            ],
            'modules' => [
                '*',
            ],
        ],
    ],
];
